In [1]:
# first get a 3D visualisation of the cells
import plotly
import plotly.graph_objects as go
import numpy as np
import pandas as pd


In [3]:
# visualise example nucleus

ex_nuc = pd.read_csv("/Users/esthomas/Mirror/Andor_Rotation/github_repo/3D_cells/G05_multiOrganelles_Linked/0_prediction_c0.model.p_cell_1_coordinates.csv")
ex_nuc.head()
ex_nuc = ex_nuc.astype(float)

In [4]:
X = ex_nuc["x"].values
Y = ex_nuc["y"].values
Z = ex_nuc["z"].values

# fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
fig = go.Figure(data=go.Scatter3d(
    x=X,
    y=Y,
    z=Z,
    mode='markers',
    marker=dict(
        size=3,            
        opacity=0.8
    )
    ))
fig.show()


In [4]:
X = ex_nuc["x"].values
Y = ex_nuc["y"].values
Z = ex_nuc["z"].values
l = len(X)

vol = np.zeros((l, l, l))

pts = (l * np.random.rand(3, 15)).astype(np.int)
vol[tuple(indices for indices in pts)] = 1

from scipy import ndimage
vol = ndimage.gaussian_filter(vol, 4)
vol /= vol.max()

# fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
fig = go.Figure(data=go.Volume(
    x=X,
    y=Y,
    z=Z,
    value=vol.flatten(),
    isomin=0.2,
    isomax=0.7,
    opacity=0.1,
    surface_count=25,
    ))
fig.show()


/var/folders/p1/99sndrn56lv71k57w35yh8n40000gn/T/ipykernel_9788/15618118.py:8: DeprecationWarning:

`np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations



In [ ]:
import numpy as np
import plotly.graph_objects as go

# Generate nicely looking random 3D-field
np.random.seed(0)
l = 30
X, Y, Z = np.mgrid[:l, :l, :l]
vol = np.zeros((l, l, l))
pts = (l * np.random.rand(3, 15)).astype(np.int)
vol[tuple(indices for indices in pts)] = 1

from scipy import ndimage
vol = ndimage.gaussian_filter(vol, 4)
vol /= vol.max()

fig = go.Figure(data=go.Volume(
    x=X.flatten(), y=Y.flatten(), z=Z.flatten(),
    value=vol.flatten(),
    isomin=0.2,
    isomax=0.7,
    opacity=0.1,
    surface_count=25,
    ))
fig.update_layout(scene_xaxis_showticklabels=False,
                  scene_yaxis_showticklabels=False,
                  scene_zaxis_showticklabels=False)
fig.show()

/var/folders/p1/99sndrn56lv71k57w35yh8n40000gn/T/ipykernel_9585/2940706395.py:9: DeprecationWarning:

`np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations



In [5]:
import pyvista as pv

points = ex_nuc.values.astype(float)

print(points)

[[ 19. 360.   0.]
 [ 20. 355.   0.]
 [ 20. 356.   0.]
 ...
 [ 29. 344.  29.]
 [ 30. 343.  29.]
 [ 30. 343.  31.]]


In [6]:
point_cloud = pv.PolyData(points)
point_cloud

PolyData (0x7fbd4d963be0)
  N Cells:	2765
  N Points:	2765
  X Bounds:	1.700e+01, 3.400e+01
  Y Bounds:	3.400e+02, 3.640e+02
  Z Bounds:	0.000e+00, 3.100e+01
  N Arrays:	0

In [7]:
np.allclose(points, point_cloud.points)

True

In [8]:
point_cloud.plot(eye_dome_lighting=True)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

In [9]:
grid = pv.StructuredGrid(X, Y, Z)
grid.plot()

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

In [10]:
ex_nuc.shape

(2765, 3)

In [11]:
points = pv.wrap(points)
surf = points.reconstruct_surface()
surf

PolyData (0x7fbd4f2f70a0)
  N Cells:	3439
  N Points:	1795
  X Bounds:	1.368e+01, 3.526e+01
  Y Bounds:	3.367e+02, 3.649e+02
  Z Bounds:	-3.320e+00, 3.154e+01
  N Arrays:	0

In [12]:
pl = pv.Plotter(shape=(1,2))
pl.add_mesh(points)
pl.add_title('Point Cloud of 3D Surface')
pl.subplot(0,1)
pl.add_mesh(surf, color=True, show_edges=True)
pl.add_title('Reconstructed Surface')
pl.show()

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

In [ ]:
'''
import numpy as np
from open3d import *    


cloud = read_point_cloud("cloud.ply") # Read the point cloud
draw_geometries([cloud]) # Visualize the point cloud     
'''
